/**
 *AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */

'use strict';
angular.module('AgavePlatformScienceAPILib', []).factory('Configuration', function () {
    return {
        //The base Uri for API calls
        BASEURI: "https://agave.iplantc.org",

        //The OAuth 2.0 access token to be set before API calls
        //TODO: Replace the oAuthAccessToken with an appropriate value
        oAuthAccessToken: ''

    };
});
//.config(['$localStorageProvider', function ($localStorageProvider) {
//    $localStorageProvider.setKeyPrefix('AgaveToGo');
//}]);

