/**
 *AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */

'use strict';
angular.module('AgavePlatformScienceAPILib', ['ngStorage']).factory('Configuration', function ($localStorage) {

    var accessToken = $localStorage.token ? $localStorage.token.access_token : 'd129ae5def616d596487e5238cef59dc';
    var baseUri = $localStorage.tenant ? $localStorage.tenant.baseUrl : "https://agave.iplantc.org";

    return {
        //The base Uri for API calls
        BASEURI: baseUri,

        //The OAuth 2.0 access token to be set before API calls
        //TODO: Replace the oAuthAccessToken with an appropriate value
        oAuthAccessToken: accessToken,

    };

    $scope.$watch('$localStorage.token', function(value){
        $timeout(function () {
            accessToken = $localStorage.token ? $localStorage.token.access_token : 'd129ae5def616d596487e5238cef59dc';
        }, 0);
    }, true);

    $scope.$watch('$localStorage.tenant', function(value){
        $timeout(function () {
            baseUri = $localStorage.tenant ? $localStorage.tenant.baseUrl : 'd129ae5def616d596487e5238cef59dc';
        }, 0);
    }, true);
});
