/**
 *AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */

function ApplicationAction() {
    this.action = undefined

}

//Make instanceof work


/**
 *TODO: Write general description for this method
 *
 * @return: ApplicationActionTypeEnum
 */
ApplicationAction.prototype.getAction = function () {

    return this.action;
}


ApplicationAction.prototype.setAction = function (value) {
    this.action = value;
}
     





