/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('ApplicationActionTypeEnum', function () {
    return {

        //TODO: Write general description for this element

        CLONE: "CLONE",


        //TODO: Write general description for this element

        PUBLISH: "PUBLISH",


        //TODO: Write general description for this element

        UNPUBLISH: "UNPUBLISH",


        //TODO: Write general description for this element

        ENABLE: "ENABLE",


        //TODO: Write general description for this element

        DISABLE: "DISABLE",

    };
});