/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('BatchSchedulerTypeEnum', function () {
    return {

        CONDOR: "CONDOR",
        CUSTOM_CONDOR: "CUSTOM_CONDOR",
        CUSTOM_GRIDENGINE: "CUSTOM_GRIDENGINE",
        CUSTOM_LOADLEVELER: "CUSTOM_LOADLEVELER",
        CUSTOM_LSF: "CUSTOM_LSF",
        CUSTOM_PBS: "CUSTOM_PBS",
        CUSTOM_SLURM: "CUSTOM_SLURM",
        CUSTOM_TORQUE: "CUSTOM_TORQUE",
        FORK: "FORK",
        LOADLEVELER: "LOADLEVELER",
        LSF: "LSF",
        MOAB: "MOAB",
        PBS: "PBS",
        SGE: "SGE",
        SLURM: "SLURM",
        TORQUE: "TORQUE",
        UNKNOWN: "UNKNOWN"

    };
});