/**
 *AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */

function ClientRequest() {
    this.name = undefined
    this.description = undefined
    this.tier = new ClientSubscriptionTierEnum("UNLIMITED")
    this.callbackUrl = undefined

}

//Make instanceof work


/**
 *The name of the client.
 *
 * @return: string
 */
ClientRequest.prototype.getName = function () {

    return this.name;
}


ClientRequest.prototype.setName = function (value) {
    this.name = value;
}


/**
 *Description of the client. This will be shown to users when authentication via OAuth web flows
 *
 * @return: string
 */
ClientRequest.prototype.getDescription = function () {

    return this.description;
}


ClientRequest.prototype.setDescription = function (value) {
    this.description = value;
}


/**
 *The access tier for this client.
 *
 * @return: ClientSubscriptionTierEnum
 */
ClientRequest.prototype.getTier = function () {

    return this.tier;
}


ClientRequest.prototype.setTier = function (value) {
    this.tier = value;
}


/**
 *Callback URL for OAuth authentication grant.
 *
 * @return: string
 */
ClientRequest.prototype.getCallbackUrl = function () {

    return this.callbackUrl;
}


ClientRequest.prototype.setCallbackUrl = function (value) {
    this.callbackUrl = value;
}
     





