/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('ClientSubscriptionTierEnum', function () {
    return {

        //TODO: Write general description for this element

        BRONZE: "BRONZE",


        //TODO: Write general description for this element

        GOLD: "GOLD",


        //TODO: Write general description for this element

        SILVER: "SILVER",


        //TODO: Write general description for this element

        UNLIMITED: "UNLIMITED",

    };
});