/**
 *AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */

function FileImportRequest() {
    this.fileType = undefined
    this.notifications = undefined
    this.fileName = undefined
    this.append = false
    this.urlToImport = undefined

}

//Make instanceof work


/**
 *The file format this file is in. Defaults to raw. This will be used in file transform operations.
 *
 * @return: string|null
 */
FileImportRequest.prototype.getFileType = function () {

    return this.fileType;
}


FileImportRequest.prototype.setFileType = function (value) {
    this.fileType = value;
}


/**
 *Notifications to set with the successful acceptance of this upload request
 *
 * @return: array|null
 */
FileImportRequest.prototype.getNotifications = function () {

    return this.notifications;
}


FileImportRequest.prototype.setNotifications = function (value) {
    this.notifications = value;
}


/**
 *The name to give the upload file. If unset, takes the original file name.
 *
 * @return: string|null
 */
FileImportRequest.prototype.getFileName = function () {

    return this.fileName;
}


FileImportRequest.prototype.setFileName = function (value) {
    this.fileName = value;
}


/**
 *Boolean flag indicating this file should be appended to the target file
 *
 * @return: bool|null
 */
FileImportRequest.prototype.getAppend = function () {

    return this.append;
}


FileImportRequest.prototype.setAppend = function (value) {
    this.append = value;
}


/**
 *The URL to import the file from. This parameter is used if not file is uploaded with this post.
 *
 * @return: string|null
 */
FileImportRequest.prototype.getUrlToImport = function () {

    return this.urlToImport;
}


FileImportRequest.prototype.setUrlToImport = function (value) {
    this.urlToImport = value;
}
     





