/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('FileManagementActionTypeEnum', function () {
    return {

        //TODO: Write general description for this element

        MKDIR: "MKDIR",


        //TODO: Write general description for this element

        RENAME: "RENAME",


        //TODO: Write general description for this element

        COPY: "COPY",


        //TODO: Write general description for this element

        MOVE: "MOVE",

    };
});