/**
 *AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */

function FilePermissionRequest() {
    this.recursive = undefined

}

//Make instanceof work
FilePermissionRequest.prototype = new PermissionRequest();

FilePermissionRequest.prototype.constructor = FilePermissionRequest;


/**
 *Should updated permissions be applied recursively. Defaults to false.
 *
 * @return: bool
 */
FilePermissionRequest.prototype.getRecursive = function () {

    return this.recursive;
}


FilePermissionRequest.prototype.setRecursive = function (value) {
    this.recursive = value;
}
     





