/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('JobActionTypeEnum', function () {
    return {

        //TODO: Write general description for this element

        RESUBMIT: "RESUBMIT",


        //TODO: Write general description for this element

        STOP: "STOP",

    };
});