/**
 *AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */

function JobAction() {
    this.action = undefined

}

//Make instanceof work


/**
 *Action to perform on the job.
 *
 * @return: JobActionTypeEnum
 */
JobAction.prototype.getAction = function () {

    return this.action;
}


JobAction.prototype.setAction = function (value) {
    this.action = value;
}
     





