/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('JobStatusTypeEnum', function () {
    return {

        //TODO: Write general description for this element

        PENDING: "PENDING",


        //TODO: Write general description for this element

        STAGING_INPUTS: "STAGING_INPUTS",


        //TODO: Write general description for this element

        CLEANING_UP: "CLEANING_UP",


        //TODO: Write general description for this element

        ARCHIVING: "ARCHIVING",


        //TODO: Write general description for this element

        STAGING_JOB: "STAGING_JOB",


        //TODO: Write general description for this element

        FINISHED: "FINISHED",


        //TODO: Write general description for this element

        KILLED: "KILLED",


        //TODO: Write general description for this element

        FAILED: "FAILED",


        //TODO: Write general description for this element

        STOPPED: "STOPPED",


        //TODO: Write general description for this element

        RUNNING: "RUNNING",


        //TODO: Write general description for this element

        PAUSED: "PAUSED",


        //TODO: Write general description for this element

        QUEUED: "QUEUED",


        //TODO: Write general description for this element

        SUBMITTING: "SUBMITTING",


        //TODO: Write general description for this element

        STAGED: "STAGED",


        //TODO: Write general description for this element

        PROCESSING_INPUTS: "PROCESSING_INPUTS",


        //TODO: Write general description for this element

        ARCHIVING_FINISHED: "ARCHIVING_FINISHED",


        //TODO: Write general description for this element

        ARCHIVING_FAILED: "ARCHIVING_FAILED",


        //TODO: Write general description for this element

        HEARTBEAT: "HEARTBEAT",

    };
});