/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('MonitorCheckResultTypeEnum', function () {
    return {

        //TODO: Write general description for this element

        FAILED: "FAILED",


        //TODO: Write general description for this element

        PASSED: "PASSED",


        //TODO: Write general description for this element

        UNKNOWN: "UNKNOWN",

    };
});