/**
 *AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */

function Notification() {
    this.event = undefined
    this.persistent = undefined
    this.url = undefined

}

//Make instanceof work


/**
 *The event you wish to recieve a notification about. Specify * for all events.
 *
 * @return: string
 */
Notification.prototype.getEvent = function () {

    return this.event;
}


Notification.prototype.setEvent = function (value) {
    this.event = value;
}


/**
 *Whether this event should remain active after it triggers the first time.
 *
 * @return: bool
 */
Notification.prototype.getPersistent = function () {

    return this.persistent;
}


Notification.prototype.setPersistent = function (value) {
    this.persistent = value;
}


/**
 *The URI to notify when the import is complete. This can be an email address or URL. If a URL is given, a POST will be made to this address. URL templating is supported. Valid template values are: ${JOB_STATUS}, ${JOB_URL}, ${JOB_ID}, ${JOB_SYSTEM}, ${JOB_NAME}, ${JOB_START_TIME}, ${JOB_END_TIME}, ${JOB_SUBMIT_TIME}, ${JOB_ARCHIVE_PATH}, ${JOB_ARCHIVE_URL}, ${JOB_ERROR}
 *
 * @return: int
 */
Notification.prototype.getUrl = function () {

    return this.url;
}


Notification.prototype.setUrl = function (value) {
    this.url = value;
}
     





