/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('PostItRequestMethodEnum', function () {
    return {

        //TODO: Write general description for this element

        GET: "GET",


        //TODO: Write general description for this element

        PUT: "PUT",


        //TODO: Write general description for this element

        POST: "POST",


        //TODO: Write general description for this element

        DELETE: "DELETE",

    };
});