/**
 *AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */

function ProfileRequest() {
    this.username = undefined
    this.email = undefined
    this.city = undefined
    this.country = undefined
    this.department = undefined
    this.fax = undefined
    this.firstName = undefined
    this.gender = undefined
    this.institution = undefined
    this.lastName = undefined
    this.phone = undefined
    this.position = undefined
    this.researchArea = undefined
    this.state = undefined
    this.status = undefined
    this.password = undefined

}

//Make instanceof work


/**
 *The api user's unique username.
 *
 * @return: string
 */
ProfileRequest.prototype.getUsername = function () {

    return this.username;
}


ProfileRequest.prototype.setUsername = function (value) {
    this.username = value;
}


/**
 *The api user's unique email address.
 *
 * @return: string
 */
ProfileRequest.prototype.getEmail = function () {

    return this.email;
}


ProfileRequest.prototype.setEmail = function (value) {
    this.email = value;
}


/**
 *The api user's city.
 *
 * @return: string|null
 */
ProfileRequest.prototype.getCity = function () {

    return this.city;
}


ProfileRequest.prototype.setCity = function (value) {
    this.city = value;
}


/**
 *The api user's country.
 *
 * @return: string|null
 */
ProfileRequest.prototype.getCountry = function () {

    return this.country;
}


ProfileRequest.prototype.setCountry = function (value) {
    this.country = value;
}


/**
 *The api user's institutional department.
 *
 * @return: string|null
 */
ProfileRequest.prototype.getDepartment = function () {

    return this.department;
}


ProfileRequest.prototype.setDepartment = function (value) {
    this.department = value;
}


/**
 *The api user's fax number.
 *
 * @return: string|null
 */
ProfileRequest.prototype.getFax = function () {

    return this.fax;
}


ProfileRequest.prototype.setFax = function (value) {
    this.fax = value;
}


/**
 *The api user's first name.
 *
 * @return: string|null
 */
ProfileRequest.prototype.getFirstName = function () {

    return this.firstName;
}


ProfileRequest.prototype.setFirstName = function (value) {
    this.firstName = value;
}


/**
 *The api user's gender. male or female.
 *
 * @return: GenderEnum|null
 */
ProfileRequest.prototype.getGender = function () {

    return this.gender;
}


ProfileRequest.prototype.setGender = function (value) {
    this.gender = value;
}


/**
 *The api user's home institution
 *
 * @return: string|null
 */
ProfileRequest.prototype.getInstitution = function () {

    return this.institution;
}


ProfileRequest.prototype.setInstitution = function (value) {
    this.institution = value;
}


/**
 *The api user's last name.
 *
 * @return: string|null
 */
ProfileRequest.prototype.getLastName = function () {

    return this.lastName;
}


ProfileRequest.prototype.setLastName = function (value) {
    this.lastName = value;
}


/**
 *The api user's phone number.
 *
 * @return: string|null
 */
ProfileRequest.prototype.getPhone = function () {

    return this.phone;
}


ProfileRequest.prototype.setPhone = function (value) {
    this.phone = value;
}


/**
 *The api user's position of employment.
 *
 * @return: string|null
 */
ProfileRequest.prototype.getPosition = function () {

    return this.position;
}


ProfileRequest.prototype.setPosition = function (value) {
    this.position = value;
}


/**
 *The api user's primary area of research.
 *
 * @return: string|null
 */
ProfileRequest.prototype.getResearchArea = function () {

    return this.researchArea;
}


ProfileRequest.prototype.setResearchArea = function (value) {
    this.researchArea = value;
}


/**
 *The api user's state.
 *
 * @return: string|null
 */
ProfileRequest.prototype.getState = function () {

    return this.state;
}


ProfileRequest.prototype.setState = function (value) {
    this.state = value;
}


/**
 *The api user's status. active or deleted.
 *
 * @return: string|null
 */
ProfileRequest.prototype.getStatus = function () {

    return this.status;
}


ProfileRequest.prototype.setStatus = function (value) {
    this.status = value;
}


/**
 *The password to set for the new user
 *
 * @return: string
 */
ProfileRequest.prototype.getPassword = function () {

    return this.password;
}


ProfileRequest.prototype.setPassword = function (value) {
    this.password = value;
}
     





