/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('SystemStatusTypeEnum', function () {
    return {

        //TODO: Write general description for this element

        UP: "UP",


        //TODO: Write general description for this element

        DOWN: "DOWN",


        //TODO: Write general description for this element

        UNKNOWN: "UNKNOWN",

    };
});