/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('SystemAuthConfigServerProtocolTypeEnum', function () {
    return {

        //TODO: Write general description for this element

        MYPROXY: "MYPROXY",


        //TODO: Write general description for this element

        MPG: "MPG",

    };
});