/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('SystemRoleTypeEnum', function () {
    return {

        //TODO: Write general description for this element

        GUEST: "GUEST",


        //TODO: Write general description for this element

        USER: "USER",


        //TODO: Write general description for this element

        PUBLISHER: "PUBLISHER",


        //TODO: Write general description for this element

        ADMIN: "ADMIN",


        //TODO: Write general description for this element

        OWNER: "OWNER",

    };
});