/**
 *agave.sdk
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('agave.sdk').factory('SystemExecutionTypeEnum', function () {
    return {

        //TODO: Write general description for this element

        CLI: "CLI",


        //TODO: Write general description for this element

        CONDOR: "CONDOR",


        //TODO: Write general description for this element

        HPC: "HPC",

    };
});