/**
 *AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */

function SystemAction() {
    this.action = undefined

}

//Make instanceof work


/**
 *Action to perform on the system.
 *
 * @return: SystemActionTypeEnum
 */
SystemAction.prototype.getAction = function () {

    return this.action;
}


SystemAction.prototype.setAction = function (value) {
    this.action = value;
}
     





