/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('SystemStorageProtocolTypeEnum', function () {
    return {

        //TODO: Write general description for this element

        FTP: "FTP",


        //TODO: Write general description for this element

        GRIDFTP: "GRIDFTP",


        //TODO: Write general description for this element

        IRODS: "IRODS",


        //TODO: Write general description for this element

        LOCAL: "LOCAL",


        //TODO: Write general description for this element

        S3: "S3",


        //TODO: Write general description for this element

        SFTP: "SFTP",

    };
});