/**
 *agave.sdk
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('agave.sdk').factory('SystemTypeEnum', function () {
    return {

        //TODO: Write general description for this element

        STORAGE: "STORAGE",


        //TODO: Write general description for this element

        EXECUTION: "EXECUTION",

    };
});