/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('SystemCredentialTypeEnum', function () {
    return {

        //TODO: Write general description for this element

        LOGIN: "LOGIN",


        //TODO: Write general description for this element

        STORAGE: "STORAGE",

    };
});