/**
 *AgavePlatformScienceAPILib
 *
 *This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */


angular.module('AgavePlatformScienceAPILib').factory('SystemStatusTypeEnum', function () {
    return {

        UP: "UP",

        DOWN: "DOWN",

        MAINTENANCE: "MAINTENANCE",

        UNKNOWN: "UNKNOWN",

    };
});