/**
 *AgavePlatformScienceAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/07/2015
 */

function TransformRequest() {
    this.nativeFormat = undefined
    this.url = undefined
    this.callbackUrl = undefined

}

//Make instanceof work


/**
 *The original file type of the file. If not given, the file type is assumed to be raw.
 *
 * @return: string
 */
TransformRequest.prototype.getNativeFormat = function () {

    return this.nativeFormat;
}


TransformRequest.prototype.setNativeFormat = function (value) {
    this.nativeFormat = value;
}


/**
 *The uri to which the transformed file will be staged.
 *
 * @return: string
 */
TransformRequest.prototype.getUrl = function () {

    return this.url;
}


TransformRequest.prototype.setUrl = function (value) {
    this.url = value;
}


/**
 *The URI to notify when the transfer is complete. This can be an email address or http URL. If a URL is given, a GET will be made to this address. URL templating is supported. Valid template values are: ${NAME}, ${SOURCE_FORMAT}, ${DEST_FORMAT}, ${STATUS}
 *
 * @return: string
 */
TransformRequest.prototype.getCallbackUrl = function () {

    return this.callbackUrl;
}


TransformRequest.prototype.setCallbackUrl = function (value) {
    this.callbackUrl = value;
}
     





